### ISSUE TITLE
missing middleware 'auth' in passport-server/routes/api.php

### ISSUE THREAD

**Issue by adnandann** [LaravelDaily/Laravel-Passport-API-Server-Client-Demo#2]

**Comment by ModestasV** [comment]
Hello,

Are you really sure about this? The auth checks for sessions while the server has no sessions available for it so user will always be non-authenticated.

Passport does require this:

> Finally, in your config/auth.php configuration file, you should set the driver option of the api authentication guard to passport. This will instruct your application to use Passport's TokenGuard when authenticating incoming API requests:

Which we have done and https://github.com/LaravelDaily/Laravel-Passport-API-Server-Client-Demo/blob/master/passport-server/config/auth.php - so there should not be an issue.

If you still feel like this is somewhat incorrect - please provide us with more description/details about the issue.

**Comment by adnandann** [comment]
Halo, 
You're right but user can manipulte api/v1/projects without any authentication or access token and i must set 'auth' in routes/api.php or in RouteServiceProvider.php

**Comment by ModestasV** [comment]
Well, that is strange... Shouldn't be like this, i'll take a look in a bit. If you want - you can make a pull-request that we could test out and merge :)

**Comment by adnandann** [comment]
There is no need, just set 'middleware' => ['**auth**:api'] instead 'middleware' => ['api']. 
It's tested, works fine... ;-)

**Comment by fgibaux** [comment]
@adnandann by doing that I think you're removing the api group middleware which is not wanted I guess.
