### ISSUE TITLE
After Authorized when 404

### ISSUE THREAD

**Issue by abkrim** [LaravelDaily/Laravel-Passport-API-Server-Client-Demo#4]
Admin is requesting permission to access your account.

Authorized and...  error

`http://passport-server.test/callback?code=def50200792cf966be653f10d228d644738bb464724f94cdb27c785e1834096ab01c0046804e4532c753be6517752c811562523eb0d859f21ed4f94c1e0fe6d5f59c8e6f8aba5472153112c08c0efd94e510bf7f1c489a063ee4ff6ce6c4aabd54aad38a0a8469fb9bbc67e7bffa8c30795854f21144ea9f59bd19aeb0d2cd70898596d68f117d8dbd42f898dd44fde32b2f022db810d13526562865618848e16cbd3d93efc6148efa8f3b6af15f9ae83f951da3257d4de3e5b4aaa4b0fa4689eb2501ae450762120055c49f23d13a13b41741cb9a4d7c611658f6c89d0461c86628b148416701a8d5933eec8b8ff1a0ee3781115f4db9c46cb20664abc0eb936f0117f16d5ae7709897fd60f396e6ecd3e3b6e1764fd5faa74c8c65acf66955b83922026c9479d2f0ef3f0c3d6792faf6d74238debe7183f0f41d617aa7acc569`

**Sorry, the page you are looking for could not be found.**

**Comment by PovilasKorop** [comment]
@abkrim are you sure you've configured everything according to the docs? All URLs and settings? Please double-check.

**Comment by abkrim** [comment]
Oops.

Reinstall all fresh.

But use MySQL instead sqlite ( i don't use mysql for test o demos) and now work fine.

A lot of thanks.
